/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as DataRouteImport } from './routes/data'
import { Route as DynamicsRouteImport } from './routes/dynamics'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as FactorsRouteImport } from './routes/factors'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as GlobeRouteImport } from './routes/globe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as ObservatoryRouteImport } from './routes/observatory'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as BenchIndexRouteImport } from './routes/bench.index'
import { Route as BenchBenchmarkIdRouteImport } from './routes/bench.$benchmarkId'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsTickerRouteImport } from './routes/markets.$ticker'
import { Route as MarketsBacktestRouteImport } from './routes/markets.backtest'
import { Route as MarketsFundamentalsRouteImport } from './routes/markets.fundamentals'
import { Route as MarketsOptionsRouteImport } from './routes/markets.options'
import { Route as MarketsResearchRouteImport } from './routes/markets.research'
import { Route as MarketsRiskRouteImport } from './routes/markets.risk'
import { Route as RealityArtifactIdRouteImport } from './routes/reality.$artifactId'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamicsRoute = DynamicsRouteImport.update({
  id: '/dynamics',
  path: '/dynamics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const FactorsRoute = FactorsRouteImport.update({
  id: '/factors',
  path: '/factors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeRoute = GlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservatoryRoute = ObservatoryRouteImport.update({
  id: '/observatory',
  path: '/observatory',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchIndexRoute = BenchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BenchRoute,
} as any)
const BenchBenchmarkIdRoute = BenchBenchmarkIdRouteImport.update({
  id: '/$benchmarkId',
  path: '/$benchmarkId',
  getParentRoute: () => BenchRoute,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsTickerRoute = MarketsTickerRouteImport.update({
  id: '/$ticker',
  path: '/$ticker',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsBacktestRoute = MarketsBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsFundamentalsRoute = MarketsFundamentalsRouteImport.update({
  id: '/fundamentals',
  path: '/fundamentals',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsOptionsRoute = MarketsOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsResearchRoute = MarketsResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsRiskRoute = MarketsRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => MarketsRoute,
} as any)
const RealityArtifactIdRoute = RealityArtifactIdRouteImport.update({
  id: '/reality/$artifactId',
  path: '/reality/$artifactId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRoute,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => RunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/bench': typeof BenchRouteWithChildren
  '/data': typeof DataRoute
  '/dynamics': typeof DynamicsRoute
  '/execution': typeof ExecutionRoute
  '/factors': typeof FactorsRoute
  '/forge': typeof ForgeRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRouteWithChildren
  '/observatory': typeof ObservatoryRoute
  '/research': typeof ResearchRoute
  '/risk': typeof RiskRoute
  '/runs': typeof RunsRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/bench/$benchmarkId': typeof BenchBenchmarkIdRoute
  '/markets/$ticker': typeof MarketsTickerRoute
  '/markets/backtest': typeof MarketsBacktestRoute
  '/markets/fundamentals': typeof MarketsFundamentalsRoute
  '/markets/options': typeof MarketsOptionsRoute
  '/markets/research': typeof MarketsResearchRoute
  '/markets/risk': typeof MarketsRiskRoute
  '/reality/$artifactId': typeof RealityArtifactIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/bench/': typeof BenchIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/data': typeof DataRoute
  '/dynamics': typeof DynamicsRoute
  '/execution': typeof ExecutionRoute
  '/factors': typeof FactorsRoute
  '/forge': typeof ForgeRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/observatory': typeof ObservatoryRoute
  '/research': typeof ResearchRoute
  '/risk': typeof RiskRoute
  '/worlds': typeof WorldsRoute
  '/bench/$benchmarkId': typeof BenchBenchmarkIdRoute
  '/markets/$ticker': typeof MarketsTickerRoute
  '/markets/backtest': typeof MarketsBacktestRoute
  '/markets/fundamentals': typeof MarketsFundamentalsRoute
  '/markets/options': typeof MarketsOptionsRoute
  '/markets/research': typeof MarketsResearchRoute
  '/markets/risk': typeof MarketsRiskRoute
  '/reality/$artifactId': typeof RealityArtifactIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/bench': typeof BenchIndexRoute
  '/markets': typeof MarketsIndexRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/bench': typeof BenchRouteWithChildren
  '/data': typeof DataRoute
  '/dynamics': typeof DynamicsRoute
  '/execution': typeof ExecutionRoute
  '/factors': typeof FactorsRoute
  '/forge': typeof ForgeRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRouteWithChildren
  '/observatory': typeof ObservatoryRoute
  '/research': typeof ResearchRoute
  '/risk': typeof RiskRoute
  '/runs': typeof RunsRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/bench/$benchmarkId': typeof BenchBenchmarkIdRoute
  '/markets/$ticker': typeof MarketsTickerRoute
  '/markets/backtest': typeof MarketsBacktestRoute
  '/markets/fundamentals': typeof MarketsFundamentalsRoute
  '/markets/options': typeof MarketsOptionsRoute
  '/markets/research': typeof MarketsResearchRoute
  '/markets/risk': typeof MarketsRiskRoute
  '/reality/$artifactId': typeof RealityArtifactIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/bench/': typeof BenchIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/bench'
    | '/data'
    | '/dynamics'
    | '/execution'
    | '/factors'
    | '/forge'
    | '/globe'
    | '/login'
    | '/markets'
    | '/observatory'
    | '/research'
    | '/risk'
    | '/runs'
    | '/worlds'
    | '/bench/$benchmarkId'
    | '/markets/$ticker'
    | '/markets/backtest'
    | '/markets/fundamentals'
    | '/markets/options'
    | '/markets/research'
    | '/markets/risk'
    | '/reality/$artifactId'
    | '/runs/$runId'
    | '/bench/'
    | '/markets/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/data'
    | '/dynamics'
    | '/execution'
    | '/factors'
    | '/forge'
    | '/globe'
    | '/login'
    | '/observatory'
    | '/research'
    | '/risk'
    | '/worlds'
    | '/bench/$benchmarkId'
    | '/markets/$ticker'
    | '/markets/backtest'
    | '/markets/fundamentals'
    | '/markets/options'
    | '/markets/research'
    | '/markets/risk'
    | '/reality/$artifactId'
    | '/runs/$runId'
    | '/bench'
    | '/markets'
    | '/runs'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/bench'
    | '/data'
    | '/dynamics'
    | '/execution'
    | '/factors'
    | '/forge'
    | '/globe'
    | '/login'
    | '/markets'
    | '/observatory'
    | '/research'
    | '/risk'
    | '/runs'
    | '/worlds'
    | '/bench/$benchmarkId'
    | '/markets/$ticker'
    | '/markets/backtest'
    | '/markets/fundamentals'
    | '/markets/options'
    | '/markets/research'
    | '/markets/risk'
    | '/reality/$artifactId'
    | '/runs/$runId'
    | '/bench/'
    | '/markets/'
    | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  BenchRoute: typeof BenchRouteWithChildren
  DataRoute: typeof DataRoute
  DynamicsRoute: typeof DynamicsRoute
  ExecutionRoute: typeof ExecutionRoute
  FactorsRoute: typeof FactorsRoute
  ForgeRoute: typeof ForgeRoute
  GlobeRoute: typeof GlobeRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  ObservatoryRoute: typeof ObservatoryRoute
  ResearchRoute: typeof ResearchRoute
  RiskRoute: typeof RiskRoute
  RunsRoute: typeof RunsRouteWithChildren
  WorldsRoute: typeof WorldsRoute
  RealityArtifactIdRoute: typeof RealityArtifactIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynamics': {
      id: '/dynamics'
      path: '/dynamics'
      fullPath: '/dynamics'
      preLoaderRoute: typeof DynamicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factors': {
      id: '/factors'
      path: '/factors'
      fullPath: '/factors'
      preLoaderRoute: typeof FactorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe': {
      id: '/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof GlobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observatory': {
      id: '/observatory'
      path: '/observatory'
      fullPath: '/observatory'
      preLoaderRoute: typeof ObservatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench/': {
      id: '/bench/'
      path: '/'
      fullPath: '/bench/'
      preLoaderRoute: typeof BenchIndexRouteImport
      parentRoute: typeof BenchRoute
    }
    '/bench/$benchmarkId': {
      id: '/bench/$benchmarkId'
      path: '/$benchmarkId'
      fullPath: '/bench/$benchmarkId'
      preLoaderRoute: typeof BenchBenchmarkIdRouteImport
      parentRoute: typeof BenchRoute
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/$ticker': {
      id: '/markets/$ticker'
      path: '/$ticker'
      fullPath: '/markets/$ticker'
      preLoaderRoute: typeof MarketsTickerRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/backtest': {
      id: '/markets/backtest'
      path: '/backtest'
      fullPath: '/markets/backtest'
      preLoaderRoute: typeof MarketsBacktestRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/fundamentals': {
      id: '/markets/fundamentals'
      path: '/fundamentals'
      fullPath: '/markets/fundamentals'
      preLoaderRoute: typeof MarketsFundamentalsRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/options': {
      id: '/markets/options'
      path: '/options'
      fullPath: '/markets/options'
      preLoaderRoute: typeof MarketsOptionsRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/research': {
      id: '/markets/research'
      path: '/research'
      fullPath: '/markets/research'
      preLoaderRoute: typeof MarketsResearchRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/risk': {
      id: '/markets/risk'
      path: '/risk'
      fullPath: '/markets/risk'
      preLoaderRoute: typeof MarketsRiskRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/reality/$artifactId': {
      id: '/reality/$artifactId'
      path: '/reality/$artifactId'
      fullPath: '/reality/$artifactId'
      preLoaderRoute: typeof RealityArtifactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof RunsRoute
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof RunsRoute
    }
  }
}

interface BenchRouteChildren {
  BenchBenchmarkIdRoute: typeof BenchBenchmarkIdRoute
  BenchIndexRoute: typeof BenchIndexRoute
}

const BenchRouteChildren: BenchRouteChildren = {
  BenchBenchmarkIdRoute: BenchBenchmarkIdRoute,
  BenchIndexRoute: BenchIndexRoute,
}

const BenchRouteWithChildren = BenchRoute._addFileChildren(BenchRouteChildren)

interface MarketsRouteChildren {
  MarketsTickerRoute: typeof MarketsTickerRoute
  MarketsBacktestRoute: typeof MarketsBacktestRoute
  MarketsFundamentalsRoute: typeof MarketsFundamentalsRoute
  MarketsOptionsRoute: typeof MarketsOptionsRoute
  MarketsResearchRoute: typeof MarketsResearchRoute
  MarketsRiskRoute: typeof MarketsRiskRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsTickerRoute: MarketsTickerRoute,
  MarketsBacktestRoute: MarketsBacktestRoute,
  MarketsFundamentalsRoute: MarketsFundamentalsRoute,
  MarketsOptionsRoute: MarketsOptionsRoute,
  MarketsResearchRoute: MarketsResearchRoute,
  MarketsRiskRoute: MarketsRiskRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

interface RunsRouteChildren {
  RunsRunIdRoute: typeof RunsRunIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsRunIdRoute: RunsRunIdRoute,
  RunsIndexRoute: RunsIndexRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  BenchRoute: BenchRouteWithChildren,
  DataRoute: DataRoute,
  DynamicsRoute: DynamicsRoute,
  ExecutionRoute: ExecutionRoute,
  FactorsRoute: FactorsRoute,
  ForgeRoute: ForgeRoute,
  GlobeRoute: GlobeRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRouteWithChildren,
  ObservatoryRoute: ObservatoryRoute,
  ResearchRoute: ResearchRoute,
  RiskRoute: RiskRoute,
  RunsRoute: RunsRouteWithChildren,
  WorldsRoute: WorldsRoute,
  RealityArtifactIdRoute: RealityArtifactIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
